//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Waste_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buyer
    {
        public int BuyerID { get; set; }
        public string BuyerName { get; set; }
        public string ContactInformation { get; set; }
        public string PurchaseHistory { get; set; }
    }
}
