//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Waste_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LFWM
    {
        public int LandfillID { get; set; }
        public Nullable<System.DateTime> WasteDate { get; set; }
        public Nullable<decimal> WeightPounds { get; set; }
        public Nullable<decimal> LandfillFees { get; set; }
    }
}
